export default {
  vi: {
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    welcome: 'Xin chào',
    home: 'Trang chủ',
    group: 'Nhóm',
    notification: 'Thông báo',
    account: 'Tài khoản',
    info: 'Thông tin Sinh Viên',
    code: 'MSSV',
    name: 'Họ Tên',
    dayofbirth: 'Ngày Sinh',
    email: 'Email',
    class: 'Lớp',
    level: 'Hệ Đào Tạo',
    special: 'Ngành',
    title: 'Đề Tài',
    numberPhone: 'Điện Thoại',
    gender: 'Giới Tính',
    term: 'Học Kỳ',
    teacher: 'Giảng Viên',
    testMajor: 'Kỹ Thuật Phần Mềm',
    detail: 'Xem chi tiết',
    clazzName: 'Lớp danh nghĩa',
    typeTraining: 'Hệ',
    updateInfo: 'Cập nhật thông tin',
    update: 'Cập nhật',
    nameTopic: 'Tên',
    note: 'Ghi chú',
    status: 'Trạng thái',
    quantityGroupMax: 'Thành viên tối đa',
    requireInput: 'Yêu cầu đầu vào',
    standradOutput: 'Yêu cầu cần đạt được',
    description: 'Mô tả',
    target: 'Mục tiêu',
    evaluation: 'Đánh giá',
    total: 'Kết quả',
  },
};
